import Navbar from '@/Navbar/navbar';
import './styles/globals.css'; 
import "@/app/news/components/Modal/modal.css";
import Dock from "./Dock/Dock"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Dock />
      </body>
    </html>
  )
}
